config/routes.rb
Aplicacion::Application.routes.draw do
  

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :pais

  resources :clientes

root :to => "home#index"
devise_for :users
resources :users, :only => :show

  devise_for :users

end

app/models/cliente.rb
class Cliente
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  
  field :avatar, :type => String
  mount_uploader :avatar, AvatarUploader
  field :Tipo_de_identificacion, :type => String
  field :Numero_de_identificacion, :type => Integer
  field :Nombre_completo, :type => String
  field :Fecha_de_nacimiento, type: Date, default: Date.parse("1989/01/01")
  field :Sexo, :type => String
  field :Pais, :type => String
  field :Departamento, :type => String
  field :Ciudad, :type => String


def self.sort( column, sort = :asc )
    if ( column )
    order_by([column.to_sym, sort.to_sym ] )
    end 
  end


  def self.search(search)
    if search
    regexp = /#{search}/
    where(Nombre_completo: regexp )
    end 
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /clientes
  # GET /clientes.json
  def index
    @per_page = 5
    params[:page] = 1 if ( params[:page].to_i < 1 )
    @page = ( params[:page].to_i > 0 ) ? params[:page].to_i - 1 : 0
    @skip = ( @per_page * @page )
    
    if ( params[:search] )
      #@clientes = Cliente.find(:all, {:conditions => ['Nombre_completo LIKE ?', "%#{params[:search]}%" ]} )
     @clientes = Cliente.search( params[:search] ).limit( @per_page ).skip( @skip )
    elsif ( params[:column] )
      @clientes = Cliente.sort( params[:column], params[:sort] ).limit( @per_page ).skip( @skip )
    else
      @clientes = Cliente.all.limit( @per_page ).skip( @skip )
    end
    
    @num_of_pages = ( @per_page.to_i > 0 ) ? ( @clientes.size / @per_page.to_f ).ceil : 1
    
    respond_to do |format|
      format.html {# index.html.erb
        if ( request.xhr? )
          render( { :partial => 'clientes/list', :locals => { :clientes => @clientes }, :layout => false } )
          return
        end
      }
      format.js {# index.js.erb
        render( :index )
      }
      format.json { render json: @clientes }
    end
end

  
  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html   {# show.html.erb
       render({ :layout => false } ) if ( request.xhr? )
       }
       format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html { # new.html.erb
        render( { :layout => false } ) if ( request.xhr? )
      }
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
    respond_to do|format|
     format.html   {
       render({ :layout => false } ) 

       }
       end
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html {
          if ( request.xhr? )
            #render json: @cliente, status: :created, location: @cliente
            render( { :partial => 'clientes/cliente', :object => @cliente, :layout => false } )
          else
            #redirect_to @cliente, notice: 'Cliente was successfully created.'
          end
        }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html {
          if ( request.xhr? )
            render( { :partial => 'clientes/cliente', :object => @cliente, :layout => false } )
          else
            redirect_to @cliente, notice: 'Cliente was successfully updated.'
          end
        }
        
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      if (request.xhr?)
        format.json { head :no_content }
        else
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
      end
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<tr BGCOLOR=#FFFFFF id="cliente_<%= cliente.id %>">
 <td><%= image_tag(cliente.avatar_url)%></td>
  <td><%= cliente.Tipo_de_identificacion %></td>
  <td><%= cliente.Numero_de_identificacion %></td>
  <td><%= cliente.Nombre_completo %></td>
  <td><%= cliente.Fecha_de_nacimiento %></td>
  <td><%= cliente.Sexo %></td>
  <td><%= cliente.Pais %></td>
  <td><%= cliente.Departamento %></td>
  <td><%= cliente.Ciudad %></td>
  <td>  <%= link_to( 'ver', cliente_path(cliente.id), { :onClick => "return( showUrlInDialog( '#{cliente_path(cliente.id)}' ) );" } ) %> </td>
    <td> <%= link_to( 'Editar', edit_cliente_path(cliente.id), { :onClick => "return( showClientForm( 'edit', '#{edit_cliente_path(cliente.id)}', '#{cliente.id}' ) );" } ) %> 
  </td>
  <td><%= link_to 'Eliminar', cliente, confirm: 'esta seguro?', method: :delete, remote:true  %></td>
</tr>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
 

 <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
<table>
<table border=2 cellspacing=2 cellpadding=3 >
<th>Avatar del Cliente</th>
<tr>



 <div class="field"><td>
      <%= f.label :avatar %><br />
      <%= image_tag( @cliente.avatar_url ) if ( @cliente.avatar? ) %><br />
      <%= f.file_field :avatar %><br />
	  <br>
      Avatar URL : <%= f.text_field :remote_avatar_url %>
      <%= f.hidden_field :avatar_cache %>
      <%= f.check_box :remove_avatar %> Quitar Avatar
	  <br>
	  <br></td>
    </div>
  </tr>
 

<th>Tipo de Documento:&nbsp;</th>
<tr>
  <div class="field">
        <td><br>
		<%= f.radio_button(:Tipo_de_identificacion,"Cedula")%>
    <%= f.label(:Tipo_de_identificacion,"Cedula")%>&nbsp; &nbsp;
	
	<%= f.radio_button(:Tipo_de_identificacion,"DNI")%>
    <%= f.label(:Tipo_de_identificacion,"DNI")%>&nbsp; &nbsp;
	
	<%= f.radio_button(:Tipo_de_identificacion,"Tarjeta de Identidad")%>
    <%= f.label(:Tipo_de_identificacion,"Tarjeta de Identidad")%> &nbsp; &nbsp;
	
	<%= f.radio_button(:Tipo_de_identificacion,"Licencia de Conduccion")%>
    <%= f.label(:Tipo_de_identificacion,"Licencia de Conduccion")%></td>
 </div></tr>
  
  <tr><td>
  <div class="field">
  <br>
    <%= f.label :Numero_de_identificacion %>
	<%= f.number_field :Numero_de_identificacion %>
  </div></td></tr>
  
  <tr><th>Datos Personales</th><tr>
  <tr><td><div class="field"><br>
    <%= f.label :Nombre_completo %>
    <%= f.text_field :Nombre_completo %>
  </div></td></tr>
 

  <tr><td>
  <div class="field"><br>
    <%= f.label :Fecha_de_nacimiento %>
    <%= f.date_select :Fecha_de_nacimiento %>
  </div></td></tr>
  
  <tr><td>
  <div class="field"><br>
  Sexo: &nbsp;
    <%= f.radio_button(:Sexo,"Masculino")%>
    <%= f.label(:Sexo,"Masculino")%> &nbsp;
	 <%= f.radio_button(:Sexo,"Femenino")%>
    <%= f.label(:Sexo,"Femenino")%>
  </div></td></tr>
  

 
<tr><td><br>
 <div class="field">
    <%= f.label :Pais %>
    <%= f.text_field :Pais %>
  </div>
  <div class="field">
    <%= f.label :Departamento %>
    <%= f.text_field :Departamento %>
  </div><div class="field">
    <%= f.label :Ciudad %>
    <%= f.text_field :Ciudad %>
  </div></td>
  </tr></table>


  
  <div class="actions"><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/_list.html.erb
<%
  def header( header_name, column_name )
    to_return = ""
       
    if ( params[:column] == column_name ) 
      if ( params[:sort] == 'asc' ) 
        to_return+="<a href=\"#\" onClick=\"return( ordenarCliente( '#{column_name}', 'desc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarCliente( '#{column_name}', 'desc' ) );\" ><img src=\"assets/arrow_up.png\" border=\"1\" /></a>"
      else 
        to_return+="<a href=\"#\" onClick=\"return( ordenarCliente( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarCliente( '#{column_name}', 'asc' ) );\" ><img src=\"assets/arrow_down.png\" border=\"1\" /></a>"
      end 
    else 
      to_return+="<a href=\"#\" onClick=\"return( ordenarCliente( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
    end     
    return( to_return.html_safe  )
  end
%>

<tr>
    <th>
     <%= header( 'Avatar', 'Avatar' ) %>
    </th>
 
    <th>
    <%=header( 'Tipo de Identificacion','Tipo_de_identificacion' ) %> 
    <!--
    <%= form_tag clientes_path, :method => 'get', :remote =>true do %>
      <%= text_field_tag :column , 'Tipo_de_identificacion' %>
     <%= text_field_tag :sort , 'asc' %>
     <%= submit_tag " Tipo de Identificacion", :name => nil %>
    <% end %>
    //-->
    </th>
  
    <th>
      <%= header( 'Numero de identificacion', 'Numero_de_identificacion' ) %>
    </th>
    
    <th>
      <%= header( 'Nombre completo', 'Nombre_completo' ) %>
    </th>
    
    <th>
     <%= header( 'Fecha de nacimiento', 'Fecha_de_nacimiento' ) %>
    </th>
    
    <th>
      <%= header( 'Sexo', 'Sexo' ) %>
    </th>

    <th>
      <%= header( 'Pais', 'Pais' ) %>
    </th>
    
    <th>
      <%= header( 'Departamento', 'Departamento' ) %>
    </th>
    
    <th>
      <%= header( 'Ciudad', 'Ciudad' ) %>
    </th>
   

    <th colspan="3">
      <%= params[:column] %><br />
      <%= params[:sort] %>
    </th>
</tr>

<%= render( clientes ) %>

app/views/clientes/_paginador.html.erb
<div id="clientpaginator">
  <%- if ( params[:page].to_i > 1 ) -%>
    <%= link_to( '<< First', clientes_path ) %>
    <%= link_to( '< Back', clientes_path( { :page => ( params[:page].to_i - 1 ) } ) ) %>
  <%- end -%>
  <%- 1.upto( @num_of_pages ) do |i| -%>
    <%= link_to( i, clientes_path( { :page => i } ) ) %>
  <%- end -%>
  <%- if ( params[:page].to_i < @num_of_pages ) -%>
    <%= link_to( 'Next >', clientes_path( { :page => ( params[:page].to_i + 1 ) } ) ) %>
    <%= link_to( 'Last >>', clientes_path( { :page => @num_of_pages } ) ) %>
  <%- end -%>
</div>
<%- content_for( :document_ready ) do -%>
  $( '#clientpaginator a' ).live( 'click', {}, function( eventObject ) {
    //$( '#client_list' ).load( this.href, function( responseText, textStatus, XMLHttpRequest ) {
    $.getScript( this.href, function( script, textStatus, jqXHR ) {
      alert( 'Datos actualizados' );
    } );
    return( false );
  } );
<%- end -%>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>
<%- if ( request.xhr? ) -%>
  <%= link_to( 'Show', cliente_path(@cliente.id), { :onClick => "jQuery( '#edit_client_form' ).dialog( 'close' );return( showUrlInDialog( '#{cliente_path(@cliente.id)}' ) );" } ) %> |
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#edit_client_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Show', @cliente %> |
  <%= link_to 'Back', clientes_path %>
<%- end -%>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag clientes_path, :method => 'get', :remote =>true do %>
  <p>
    <%= text_field_tag :search , params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<h2><a href="#" onClick="return( actualizarCliente( ) );" >Actualizar</a></h2>



<h2>Lista de Clientes</h2>
<br>
<br>

<table border=2 cellspacing=1 cellpadding=2 bordercolor="black" BGCOLOR=#E0F8F7 id="client_list">
  <%= render( { :partial => 'clientes/list', :locals => { :clientes => @clientes } } ) %>
</table>

<%= render ( { :partial => 'clientes/paginador' } ) %>

<br />
<h1>
<!--<a href="javascript:showUrlInDialog('clientes/new')">Nuevo Cliente</a> |//-->
<a href="#" onClick="return( showClientForm( 'new', 'clientes/new') );">Nuevo Cliente</a>
</h1>

app/views/clientes/index.js.erb
alert("xxxx");
jQuery( "#client_list" ).html( "<%= escape_javascript( render( { :partial => 'clientes/list', :locals => { :clientes => @clientes } } ) ) %>");
jQuery( '#clientpaginator' ).html( "<%= escape_javascript( render( { :partial => 'clientes/paginador' } ) ) %>");

app/views/clientes/new.html.erb
<h1>New cliente</h1>



<%= render( { :partial => 'clientes/form' } ) %>
<%- if ( request.xhr? ) -%>
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#new_client_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Back', clientes_path %>
<%- end -%>

app/views/clientes/show.html.erb
<table>
<table border=2 cellspacing=1 cellpadding=2 bordercolor="black" BGCOLOR=#E0F8F7>
<tr>
<td>
<%= image_tag(@cliente.avatar_url)%>
<%= @remote_avatar_url %></td> 
</tr>

<h3>Datos del Cliente</h3>


<tr><td>
  <b>Tipo de identificacion:</b>
  <%= @cliente.Tipo_de_identificacion %>
</td></tr>


<tr><td>
  <b>Numero de identificacion:</b>
  <%= @cliente.Numero_de_identificacion %>
</td></tr>

<tr><td>
  <b>Nombre completo:</b>
  <%= @cliente.Nombre_completo %>
</td></tr>

<tr><td>
  <b>Fecha de nacimiento:</b>
  <%= @cliente.Fecha_de_nacimiento %>
</td></tr>

<tr><td>
  <b>Sexo:</b>
  <%= @cliente.Sexo %>
</td></tr>

<tr><td>
  <b>Pais:</b>
  <%= @cliente.Pais %>
</td></tr>

<tr><td>
  <b>Departamento:</b>
  <%= @cliente.Departamento %>
</td></tr>

<tr><td>
  <b>Ciudad:</b>
  <%= @cliente.Ciudad %>
</td></tr>
</table>

<%- if ( request.xhr? ) -%>
  <td> <%= link_to( 'Editar', edit_cliente_path(@cliente.id), { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( showClientForm( 'edit', '#{edit_cliente_path(@cliente.id)}', '#{@cliente.id}' ) );" } ) %>  |
  <%= link_to 'Cerrar', '#', { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Edit', edit_cliente_path(@cliente) %> |
  <%= link_to 'Back', clientes_path %>
<%- end -%>