config/routes.rb
Aplicacion::Application.routes.draw do
  

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :pais

  resources :clientes

root :to => "home#index"
devise_for :users
resources :users, :only => :show

  devise_for :users

end

app/models/departamento.rb
class Departamento
include Mongoid::Document
include Mongoid::MultiParameterAttributes

field :nombre, :type => String
  field :codigo, :type => Integer
  field :pais_codigo, :type => Integer


def self.sort( column, sort = :asc )
    if ( column )
    order_by([column.to_sym, sort.to_sym ] )
    end 
  end


  def self.search(search)
    if search
    regexp = /#{search}/
    where(nombre: regexp )
    end 
  end
  
  end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
    before_filter :authenticate_user!

  # GET /departamentos
  # GET /departamentos.json
  def index
    
    @per_page = 5
    params[:page] = 1 if ( params[:page].to_i < 1 )
    @page = ( params[:page].to_i > 0 ) ? params[:page].to_i - 1 : 0
    @skip = ( @per_page * @page )

       
       
        
    if ( params[:search] )
      #@clientes = Cliente.find(:all, {:conditions => ['Nombre_completo LIKE ?', "%#{params[:search]}%" ]} )
     @departamentos = Departamento.search( params[:search] ).limit(@per_page).skip(@skip)
    elsif ( params[:column] )
      @departamentos = Departamento.sort( params[:column], params[:sort] ).limit(@per_page).skip(@skip)
    else
      @departamentos = Departamento.all.limit(@per_page).skip(@skip)
    end
       
           @num_of_pages = ( @per_page.to_i > 0 ) ? ( @departamentos.size / @per_page.to_f ).ceil : 1

       
       
       respond_to do |format|
      format.html {# index.html.erb
        if ( request.xhr? )
          render( { :partial => 'departamentos/list', :locals => { :departamentos => @departamentos }, :layout => false } )
          return
        end
      }
      format.js {# index.js.erb
        render( :index )
      }
      format.json { render json: @departamentos }
    end
end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      format.html {# show.html.erb
      render({:layout=> false}) if(request.xhr?)
    }
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  # GET /departamentos/new.json
  def new
    @departamento = Departamento.new

    respond_to do |format|
      format.html {# new.html.erb
      render({:layout=> false}) if(request.xhr?)
      }
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
    
    respond_to do |format|
      format.html{
      render({:layout=>false})
      }
    end
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(params[:departamento])

    respond_to do |format|
      if @departamento.save
        format.html{
        if(request.xhr?)
        render({:partial=> 'departamentos/departamento', :object=> @departamento, :layout=> false})
        else
        #format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
      end
      }

      format.json { render json: @departamento, status: :created, location: @departamento }
      else
        format.html { render action: "new" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departamentos/1
  # PUT /departamentos/1.json
  def update
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      if @departamento.update_attributes(params[:departamento])
        format.html{
          if(request.xhr?)
            render( { :partial => 'departamentos/departamento', :object => @departamento, :layout => false } )
          else
         redirect_to @departamento, notice: 'Departamento was successfully updated.' 
         end
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy

    respond_to do |format|
      if(request.xhr?)
      format.json { head :no_content }
      else
      format.html { redirect_to departamentos_url }
      format.json { head :no_content }
    end
    end
  end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_departamento.html.erb
 <tr BGCOLOR=#FFFFFF id="departamento_<%= departamento.id %>">
    <td><%= departamento.nombre %></td>
    <td><%= departamento.codigo %></td>
    <td><%= departamento.pais_codigo %></td>
  <td>  <%= link_to( 'ver', departamento_path(departamento.id), { :onClick => "return( showUrlInDialog( '#{departamento_path(departamento.id)}' ) );" } ) %> </td>
    <td> <%= link_to( 'Editar', edit_departamento_path(departamento.id), { :onClick => "return( showDepartamentForm( 'edit', '#{edit_departamento_path(departamento.id)}', '#{departamento.id}' ) );" } ) %> 
  <td><%= link_to 'Eliminar', departamento, confirm: 'esta seguro?', method: :delete, remote:true  %></td>

</tr>

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :pais_codigo %><br />
    <%= f.number_field :pais_codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/_list.html.erb
<%
  def header( header_name, column_name )
    to_return = ""
       
    if ( params[:column] == column_name ) 
      if ( params[:sort] == 'asc' ) 
        to_return+="<a href=\"#\" onClick=\"return( ordenarDepartamento( '#{column_name}', 'desc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarDepartamento( '#{column_name}', 'desc' ) );\" ><img src=\"assets/arrow_up.png\" border=\"1\" /></a>"
      else 
        to_return+="<a href=\"#\" onClick=\"return( ordenarDepartamento( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarDepartamento( '#{column_name}', 'asc' ) );\" ><img src=\"assets/arrow_down.png\" border=\"1\" /></a>"
      end 
    else 
      to_return+="<a href=\"#\" onClick=\"return( ordenarDepartamento( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
    end     
    return( to_return.html_safe  )
  end
%>

  <tr>
    <th>
     <%= header( 'Nombre', 'nombre' ) %>
    </th>
    
    <th>
     <%= header( 'Codigo', 'codigo' ) %>
    </th>
    <th>
     <%= header( 'Codigo Pais', 'pais_codigo' ) %>
    </th>
    
    <th colspan="3">
      <%= params[:column] %><br />
      <%= params[:sort] %>
    </th>
</tr>

    
 <%= render( departamentos ) %>
   

app/views/departamentos/_paginador.html.erb
<div id="departamentpaginator">
  <%- if ( params[:page].to_i > 1 ) -%>
    <%= link_to( '<< First', departamento_path ) %>
    <%= link_to( '< Back', departamento_path( { :page => ( params[:page].to_i - 1 ) } ) ) %>
  <%- end -%>
  <%- 1.upto( @num_of_pages ) do |i| -%>
    <%= link_to( i, departamento_path( { :page => i } ) ) %>
  <%- end -%>
  <%- if ( params[:page].to_i < @num_of_pages ) -%>
    <%= link_to( 'Next >', departamento_path( { :page => ( params[:page].to_i + 1 ) } ) ) %>
    <%= link_to( 'Last >>', departamento_path( { :page => @num_of_pages } ) ) %>
  <%- end -%>
</div>
<%- content_for( :document_ready ) do -%>
  $( '#departamentpaginator a' ).live( 'click', {}, function( eventObject ) {
    //$( '#departament_list' ).load( this.href, function( responseText, textStatus, XMLHttpRequest ) {
    $.getScript( this.href, function( script, textStatus, jqXHR ) {
      alert( 'Datos actualizados' );
    } );
    return( false );
  } );
<%- end -%>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>





<%= render 'form' %>
<%- if ( request.xhr? ) -%>
  <%= link_to( 'Show', departamento_path(@departamento.id), { :onClick => "jQuery( '#edit_departament_form' ).dialog( 'close' );return( showUrlInDialog( '#{departamento_path(@departamento.id)}' ) );" } ) %> |
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#edit_departament_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Show', @cliente %> |
  <%= link_to 'Back', clientes_path %>
<%- end -%>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag departamentos_path, :method => 'get', :remote =>true do %>
  <p>
    <%= text_field_tag :search , params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h2><a href="#" onClick="return( actualizarDepartamento( ) );" >Actualizar</a></h2>


<h1>Listing departamentos</h1>

<table border=2 cellspacing=1 cellpadding=2 bordercolor="black" BGCOLOR=#E0F8F7 id="departament_list">
 <%= render( { :partial => 'departamentos/list', :locals => { :departamentos => @departamentos } } ) %>

</table>
<br />

<%= render ( { :partial => 'departamentos/paginador' } ) %>
<h2>
<a href="#" onClick="return( showDepartamentForm( 'new', 'departamentos/new') );">Nuevo Departamento</a>
</h2>

app/views/departamentos/index.js.erb
alert("xxxx");
jQuery( "#departament_list" ).html( "<%= escape_javascript( render( { :partial => 'departamentos/list', :locals => { :departamentos => @departamentos } } ) ) %>");
jQuery( '#departamentpaginator' ).html( "<%= escape_javascript( render( { :partial => 'departamentos/paginador' } ) ) %>");

app/views/departamentos/new.html.erb
<h1>New departamento</h1>




<%= render( { :partial => 'departamentos/form' } ) %>
<%- if ( request.xhr? ) -%>
 <%= link_to 'Close', '#', { :onClick => "jQuery( '#new_departament_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
<%= link_to 'Back', departamentos_path %>
<%- end -%>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @departamento.nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @departamento.codigo %>
</p>

<p>
  <b>Pais codigo:</b>
  <%= @departamento.pais_codigo %>
</p>


<%- if ( request.xhr? ) -%>
  <td> <%= link_to( 'Editar', edit_departamento_path(@departamento.id), { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( showDepartamentForm( 'edit', '#{edit_departamento_path(@departamento.id)}', '#{@departamento.id}' ) );" } ) %>  |
  <%= link_to 'Cerrar', '#', { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Edit', edit_departamento_path(@departamento) %> |
  <%= link_to 'Back', departamentos_path %>
<%- end -%>