config/routes.rb
Aplicacion::Application.routes.draw do
  

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :pais

  resources :clientes

root :to => "home#index"
devise_for :users
resources :users, :only => :show

  devise_for :users

end

app/models/ciudade.rb
class Ciudade
include Mongoid::Document
  include Mongoid::MultiParameterAttributes


field :nombre, :type => String
  field :codigo, :type => Integer
  field :departamento_codigo, :type => Integer
  
  
  
 
def self.sort( column, sort = :asc )
    if ( column )
    order_by([column.to_sym, sort.to_sym ] )
    end 
  end


  def self.search(search)
    if search
    regexp = /#{search}/
    where(nombre: regexp )
    end 
  end 
end

app/controllers/ciudades_controller.rb
class CiudadesController < ApplicationController
    before_filter :authenticate_user!

  # GET /ciudades
  # GET /ciudades.json
  def index

 @per_page = 2
    params[:page] = 1 if ( params[:page].to_i < 1 )
    @page = ( params[:page].to_i > 0 ) ? params[:page].to_i - 1 : 0
    @skip = ( @per_page * @page )



    if ( params[:search] )
     @ciudades = Ciudade.search( params[:search] ).limit( @per_page ).skip( @skip )
    elsif ( params[:column] )
      @ciudades = Ciudade.sort( params[:column], params[:sort] ).limit( @per_page ).skip( @skip )
    else
      @ciudades = Ciudade.all.limit( @per_page ).skip( @skip )
    end
    

@num_of_pages = ( @per_page.to_i > 0 ) ? ( @ciudades.size / @per_page.to_f ).ceil : 1

    
    respond_to do |format|
      format.html {# index.html.erb
        if ( request.xhr? )
          render( { :partial => 'ciudades/list', :locals => { :ciudades => @ciudades}, :layout => false } )
          return
        end
      }
      format.js {# index.js.erb
        render( :index )
      }
      format.json { render json: @ciudades }
    end
  end

  # GET /ciudades/1
  # GET /ciudades/1.json
  def show
    @ciudade = Ciudade.find(params[:id])

    respond_to do |format|
      format.html {# show.html.erb
       render({:layout=>false} ) if(request.xhr?)
      }
      format.json { render json: @ciudade }
    end
  end

  # GET /ciudades/new
  # GET /ciudades/new.json
  def new
    @ciudade = Ciudade.new

    respond_to do |format|
      format.html{ # new.html.erb
     render({:layout=>false }) if(request.xhr?)
     } 
      format.json { render json: @ciudade }
    end
  end

  # GET /ciudades/1/edit
  def edit
    @ciudade = Ciudade.find(params[:id])
     respond_to do|format|
     format.html   {
       render({ :layout => false } )
       }
       end
  end

  # POST /ciudades
  # POST /ciudades.json
  def create
    @ciudade = Ciudade.new(params[:ciudade])

    respond_to do |format|
      if @ciudade.save
        format.html{
        if(request.xhr?)
          render( { :partial => 'ciudades/ciudade', :object => @ciudade, :layout => false } )
          else
          #format.html { redirect_to @ciudade, notice: 'Ciudade was successfully created.' }
        end
        }
        format.json { render json: @ciudade, status: :created, location: @ciudade }
      else
        format.html { render action: "new" }
        format.json { render json: @ciudade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ciudades/1
  # PUT /ciudades/1.json
  def update
    @ciudade = Ciudade.find(params[:id])

    respond_to do |format|
      if @ciudade.update_attributes(params[:ciudade])
         format.html {
          if ( request.xhr? )
            render( { :partial => 'ciudades/ciudade', :object => @ciudade, :layout => false } )
        else
        format.html { redirect_to @ciudade, notice: 'Ciudade was successfully updated.' }
         end
         }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ciudade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudades/1
  # DELETE /ciudades/1.json
  def destroy
    @ciudade = Ciudade.find(params[:id])
    @ciudade.destroy

    respond_to do |format|
      if(request.xhr?)
      format.json{head:no_content}
      else
      format.html { redirect_to ciudades_url }
      format.json { head :no_content }
    end
    end
  end
end

app/helpers/ciudades_helper.rb
module CiudadesHelper
end

app/views/ciudades/_ciudade.html.erb
<tr BGCOLOR=#FFFFFF id="ciudade_<%= ciudade.id %>">
 <td><%= ciudade.nombre %></td>
    <td><%= ciudade.codigo %></td>
    <td><%= ciudade.departamento_codigo %></td>
<td>  <%= link_to( 'ver', ciudade_path(ciudade.id), { :onClick => "return( showUrlInDialog( '#{ciudade_path(ciudade.id)}' ) );" } ) %> </td>
 <td> <%= link_to( 'Editar', edit_ciudade_path(ciudade.id), { :onClick => "return( showCiudadForm( 'edit', '#{edit_ciudade_path(ciudade.id)}', '#{ciudade.id}' ) );" } ) %> 
  </td>
  <td><%= link_to 'Eliminar', ciudade, confirm: 'esta seguro?', method: :delete, remote:true  %></td>
</tr>

app/views/ciudades/_form.html.erb
<%= form_for(@ciudade) do |f| %>
  <% if @ciudade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudade.errors.count, "error") %> prohibited this ciudade from being saved:</h2>

      <ul>
      <% @ciudade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :departamento_codigo %><br />
    <%= f.number_field :departamento_codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ciudades/_list.html.erb
<%
  def header( header_name, column_name )
    to_return = ""
       
    if ( params[:column] == column_name ) 
      if ( params[:sort] == 'asc' ) 
        to_return+="<a href=\"#\" onClick=\"return( ordenarCiudad( '#{column_name}', 'desc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarCiudad( '#{column_name}', 'desc' ) );\" ><img src=\"assets/arrow_up.png\" border=\"1\" /></a>"
      else 
        to_return+="<a href=\"#\" onClick=\"return( ordenarCiudad( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarCiudad( '#{column_name}', 'asc' ) );\" ><img src=\"assets/arrow_down.png\" border=\"1\" /></a>"
      end 
    else 
      to_return+="<a href=\"#\" onClick=\"return( ordenarCiudad( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
    end     
    return( to_return.html_safe  )
  end
%>


<tr>
    <th>
     <%= header( 'Nombre', 'nombre' ) %>
    </th>
  
    <th>
     <%= header( 'Codigo', 'codigo' ) %>
    </th>
 
    <th>
     <%= header( 'Codigo Departamento', 'departamento_codigo' ) %>
    </th>

 
 
    <th colspan="3">
      <%= params[:column] %><br />
      <%= params[:sort] %>
    </th>
</tr>

<%= render( ciudades ) %>

app/views/ciudades/_paginador.html.erb
<div id="ciudadpaginator">
  <%- if ( params[:page].to_i > 1 ) -%>
    <%= link_to( '<< First', ciudades_path ) %>
    <%= link_to( '< Back', ciudades_path( { :page => ( params[:page].to_i - 1 ) } ) ) %>
  <%- end -%>
  <%- 1.upto( @num_of_pages ) do |i| -%>
    <%= link_to( i, ciudades_path( { :page => i } ) ) %>
  <%- end -%>
  <%- if ( params[:page].to_i < @num_of_pages ) -%>
    <%= link_to( 'Next >', ciudades_path( { :page => ( params[:page].to_i + 1 ) } ) ) %>
    <%= link_to( 'Last >>', ciudades_path( { :page => @num_of_pages } ) ) %>
  <%- end -%>
</div>
<%- content_for( :document_ready ) do -%>
  $( '#ciudadpaginator a' ).live( 'click', {}, function( eventObject ) {
    //$( '#ciudad_list' ).load( this.href, function( responseText, textStatus, XMLHttpRequest ) {
    $.getScript( this.href, function( script, textStatus, jqXHR ) {
      alert( 'Datos actualizados' );
    } );
    return( false );
  } );
<%- end -%>

app/views/ciudades/edit.html.erb
<h1>Editing ciudad</h1>

<%= render 'form' %>
<%- if ( request.xhr? ) -%>
  <%= link_to( 'Show', ciudade_path(@ciudade.id), { :onClick => "jQuery( '#edit_ciudad_form' ).dialog( 'close' );return( showUrlInDialog( '#{ciudade_path(@ciudade.id)}' ) );" } ) %> |
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#edit_ciudad_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
<%= link_to 'Show', @ciudade %> |
<%= link_to 'Back', ciudades_path %>
<%- end -%>

app/views/ciudades/index.html.erb
<p id="notice"><%= notice %></p>



<%= form_tag ciudades_path, :method => 'get', :remote =>true do %>
  <p>
    <%= text_field_tag :search , params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<a href="#" onClick="return( actualizarCiudad( ) );" >Actualizar</a></h2>


<h1>Listing ciudades</h1>

<br>
<br>


<table border=2 cellspacing=1 cellpadding=2 bordercolor="black" BGCOLOR=#E0F8F7 id="ciudad_list">
<%= render( { :partial => 'ciudades/list', :locals => { :ciudades => @ciudades } } ) %>
</table>

<%= render ( { :partial => 'ciudades/paginador' } ) %>

<br />
<h1>
<a href="#" onClick="return( showCiudadForm( 'new', 'ciudades/new') );">Nueva Ciudad</a>
</h1>

app/views/ciudades/index.js.erb
alert("xxxx");
jQuery( "#ciudad_list" ).html( "<%= escape_javascript( render( { :partial => 'ciudades/list', :locals => { :ciudades => @ciudades } } ) ) %>");
jQuery( '#ciudadpaginator' ).html( "<%= escape_javascript( render( { :partial => 'ciudades/paginador' } ) ) %>");

app/views/ciudades/new.html.erb
<h1>New ciudad</h1>

<%= render 'form' %>
<%- if ( request.xhr? ) -%>
 <%= link_to 'Close', '#', { :onClick => "jQuery( '#new_ciudad_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
<%= link_to 'Back', ciudades_path %>
<% end %>

app/views/ciudades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @ciudade.nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @ciudade.codigo %>
</p>

<p>
  <b>Departamento codigo:</b>
  <%= @ciudade.departamento_codigo %>
</p>

<%- if ( request.xhr? ) -%>
  <td> <%= link_to( 'Editar', edit_ciudade_path(@ciudade.id), { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( showCiudadForm( 'edit', '#{edit_ciudade_path(@ciudade.id)}', '#{@ciudade.id}' ) );" } ) %>  |
  <%= link_to 'Cerrar', '#', { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( false );" } %>
<%- else -%>
<%= link_to 'Edit', edit_ciudade_path(@ciudade) %> |
<%= link_to 'Back', ciudades_path %>
<%- end -%>