config/routes.rb
Aplicacion::Application.routes.draw do
  

  resources :ciudades

  resources :departamentos

  resources :paises

  resources :pais

  resources :clientes

root :to => "home#index"
devise_for :users
resources :users, :only => :show

  devise_for :users

end

app/controllers/paises_controller.rb
class PaisesController < ApplicationController
   before_filter :authenticate_user!
  
  # GET /paises
  # GET /paises.json
  def index

    
    @per_page = 5
    params[:page] = 1 if ( params[:page].to_i < 1 )
    @page = ( params[:page].to_i > 0 ) ? params[:page].to_i - 1 : 0
    @skip = ( @per_page * @page )
    

if ( params[:search] )
      
     @paises = Paise.search( params[:search] ).limit(@per_page).skip(@skip)
    elsif ( params[:column] )
      @paises = Paise.sort( params[:column], params[:sort] ).limit(@per_page).skip(@skip)
    else
      @paises = Paise.all.limit(@per_page).skip(@skip)
    end  
  
  @num_of_pages = ( @per_page.to_i > 0 ) ? ( @paises.size / @per_page.to_f ).ceil : 1


respond_to do |format|
      format.html {# index.html.erb
        if ( request.xhr? )
          render( { :partial => 'paises/list', :locals => { :paises => @paises }, :layout => false } )
          return
        end
      }
      format.js {# index.js.erb
        render( :index )
      }
      format.json { render json: @paises }
    end
  end

  # GET /paises/1
  # GET /paises/1.json
  def show
    @paise = Paise.find(params[:id])

    respond_to do |format|
      format.html   {# show.html.erb
       render({ :layout => false } ) if ( request.xhr? )
       }
       format.json { render json: @paise }
    end
  end

  # GET /paises/new
  # GET /paises/new.json
  def new
    @paise = Paise.new
  
    respond_to do |format|
      format.html { # new.html.erb
        render( { :layout => false } ) if ( request.xhr? )
      }
      format.json { render json: @paise }
    end
  end

  # GET /paises/1/edit
  def edit
    @paise = Paise.find(params[:id])
    respond_to do|format|
     format.html   {
       render({ :layout => false } ) 
       }
    end
  end

  # POST /paises
  # POST /paises.json
  def create
    @paise = Paise.new(params[:paise])

    respond_to do |format|
      if @paise.save
         format.html {
          if ( request.xhr? )
            #render json: @paise, status: :created, location: @paise
            render( { :partial => 'paises/paise', :object => @paise, :layout => false } )
          else
            #redirect_to @paise, notice: 'Paise was successfully created.'
          end
        }
        format.json { render json: @paise, status: :created, location: @paise }
      else
        format.html { render action: "new" }
        format.json { render json: @paise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paises/1
  # PUT /paises/1.json
  def update
    @paise = Paise.find(params[:id])

    respond_to do |format|
      if @paise.update_attributes(params[:paise])
        format.html{
        if(request.xhr?)
        render({:partial => 'paises/paise', :object => @paise , :layout =>false})
          else
          redirect_to @paise, notice: 'Paise was successfully updated.' 
        end
      }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paises/1
  # DELETE /paises/1.json
  def destroy
    @paise = Paise.find(params[:id])
    @paise.destroy

    respond_to do |format|
      if(request.xhr?)
        format.json { head :no_content }
        else
        format.html { redirect_to paises_url }
        format.json { head :no_content } 
      end
      end
    end
  end

app/helpers/paises_helper.rb
module PaisesHelper
end

app/views/paises/_form.html.erb
<%= form_for(@paise) do |f| %>
  <% if @paise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paise.errors.count, "error") %> prohibited this paise from being saved:</h2>

      <ul>
      <% @paise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paises/_list.html.erb
<%
  def header( header_name, column_name )
    to_return = ""
       
    if ( params[:column] == column_name ) 
      if ( params[:sort] == 'asc' ) 
        to_return+="<a href=\"#\" onClick=\"return( ordenarPais( '#{column_name}', 'desc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarPais( '#{column_name}', 'desc' ) );\" ><img src=\"assets/arrow_up.png\" border=\"1\" /></a>"
      else 
        to_return+="<a href=\"#\" onClick=\"return( ordenarPais( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
        to_return+="<a href=\"#\" onClick=\"return( ordenarPais( '#{column_name}', 'asc' ) );\" ><img src=\"assets/arrow_down.png\" border=\"1\" /></a>"
      end 
    else 
      to_return+="<a href=\"#\" onClick=\"return( ordenarPais( '#{column_name}', 'asc' ) );\" >#{header_name}</a>"
    end     
    return( to_return.html_safe  )
  end
%>

<tr>
    <th>
     <%= header( 'Nombre', 'nombre' ) %>
    </th>
 
    <th>
     <%= header( 'Codigo', 'codigo' ) %>
    </th>
 

    <th colspan="3">
      </th>
  </tr>

<%= render( paises ) %>

app/views/paises/_paginador.html.erb
<div id="paisepaginator">
  <%- if ( params[:page].to_i > 1 ) -%>
    <%= link_to( '<< First', paises_path ) %>
    <%= link_to( '< Back', paises_path( { :page => ( params[:page].to_i - 1 ) } ) ) %>
  <%- end -%>
  <%- 1.upto( @num_of_pages ) do |i| -%>
    <%= link_to( i, paises_path( { :page => i } ) ) %>
  <%- end -%>
  <%- if ( params[:page].to_i < @num_of_pages ) -%>
    <%= link_to( 'Next >', paises_path( { :page => ( params[:page].to_i + 1 ) } ) ) %>
    <%= link_to( 'Last >>', paises_path( { :page => @num_of_pages } ) ) %>
  <%- end -%>
</div>
<%- content_for( :document_ready ) do -%>
  $( '#paisepaginator a' ).live( 'click', {}, function( eventObject ) {
    //$( '#paise_list' ).load( this.href, function( responseText, textStatus, XMLHttpRequest ) {
    $.getScript( this.href, function( script, textStatus, jqXHR ) {
      alert( 'Datos actualizados' );
    } );
    return( false );
  } );
<%- end -%>

app/views/paises/_paise.html.erb
<tr BGCOLOR=#FFFFFF id="paise_<%= paise.id %>">
    <td><%= paise.nombre %></td>
    <td><%= paise.codigo %></td>
     <td>  <%= link_to( 'ver', paise_path(paise.id), { :onClick => "return( showUrlInDialog( '#{paise_path(paise.id)}' ) );" } ) %> </td>
<td> <%= link_to( 'Editar', edit_paise_path(paise.id), { :onClick => "return( showPaisForm( 'edit', '#{edit_paise_path(paise.id)}', '#{paise.id}' ) );" } ) %> </td>
    <td><%= link_to 'Eliminar', paise, confirm: 'Are you sure?', method: :delete , remote: true%></td>
  </tr>

app/views/paises/edit.html.erb
<h1>Editing paise</h1>

<%= render 'form' %>
<%- if ( request.xhr? ) -%>
  <%= link_to( 'Show', paise_path(@paise.id), { :onClick => "jQuery( '#edit_paise_form' ).dialog( 'close' );return( showUrlInDialog( '#{paise_path(@paise.id)}' ) );" } ) %> |
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#edit_paise_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
<%= link_to 'Show', @paise %> |
<%= link_to 'Back', paises_path %>
<%-end-%>

app/views/paises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing paises</h1>



<%= form_tag paises_path, :method => 'get', :remote =>true do %>
  <p>
    <%= text_field_tag :search , params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h2><a href="#" onClick="return( actualizarPais( ) );" >Actualizar</a></h2>


<table border=2 cellspacing=1 cellpadding=2 bordercolor="black" BGCOLOR=#E0F8F7  id="paise_list">
<%= render( { :partial => 'paises/list', :locals => { :paises => @paises } } ) %>
 
</table>

<%= render ( { :partial => 'paises/paginador' } ) %>

<br />

<br />
<h1>
<a href="#" onClick="return( showPaisForm( 'new', 'paises/new') );">Nuevo pais 2</a>
</h1>

app/views/paises/index.js.erb
alert("xxxx");
jQuery( "#paise_list" ).html( "<%= escape_javascript( render( { :partial => 'paises/list', :locals => { :paises => @paises } } ) ) %>");
jQuery( '#paisepaginator' ).html( "<%= escape_javascript( render( { :partial => 'paises/paginador' } ) ) %>");

app/views/paises/new.html.erb
<h1>New pais</h1>


<%= render( { :partial => 'paises/form' } ) %>
<%- if ( request.xhr? ) -%>
  <%= link_to 'Close', '#', { :onClick => "jQuery( '#new_paise_form' ).dialog( 'close' );return( false );" } %>
<%- else -%>
  <%= link_to 'Back', paises_path %>
<%- end -%>

app/views/paises/show.html.erb
<p id="notice"><%= notice %></p>

    <tr>
      <b>Nombre:</b>
      <%= @paise.nombre %>
    </tr>
    
    <tr>
      <b>Codigo:</b>
      <%= @paise.codigo %>  
    </tr>


<%- if( request.xhr?)-%>
<%= link_to( 'Editar', edit_paise_path(@paise.id), { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( showPaisForm( 'edit', '#{edit_paise_path(@paise.id)}', '#{@paise.id}' ) );" } ) %>  |
  <%= link_to 'Cerrar', '#', { :onClick => "jQuery( '#theUrlDialog' ).dialog( 'close' );return( false );" } %>
  <%- else -%>
<%= link_to 'Edit', edit_paise_path(@paise) %> |
<%= link_to 'Back', paises_path %>
<%- end -%>